// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQt2F-DmionQl76HKThyUZlzXciLr16uU',
    appId: '1:204519090912:web:90e8543713169c94607e85',
    messagingSenderId: '204519090912',
    projectId: 'testing-dedb6',
    authDomain: 'testing-dedb6.firebaseapp.com',
    storageBucket: 'testing-dedb6.appspot.com',
    measurementId: 'G-1DWSD9D1GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb98PKu8q5C6VuW8K__TNnYkSNGSW9-W8',
    appId: '1:204519090912:android:15b9b19ae5c4695b607e85',
    messagingSenderId: '204519090912',
    projectId: 'testing-dedb6',
    storageBucket: 'testing-dedb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UpM032_42Uza439IOpsa4HGVOJDQiPo',
    appId: '1:204519090912:ios:6790beb65ca7c854607e85',
    messagingSenderId: '204519090912',
    projectId: 'testing-dedb6',
    storageBucket: 'testing-dedb6.appspot.com',
    androidClientId: '204519090912-9eftu5c3nc8ljoe5aaucgunm50v508hq.apps.googleusercontent.com',
    iosClientId: '204519090912-o4cj9tmfk81fcri9cfql03ntkg4nk1n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanoFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UpM032_42Uza439IOpsa4HGVOJDQiPo',
    appId: '1:204519090912:ios:6790beb65ca7c854607e85',
    messagingSenderId: '204519090912',
    projectId: 'testing-dedb6',
    storageBucket: 'testing-dedb6.appspot.com',
    androidClientId: '204519090912-9eftu5c3nc8ljoe5aaucgunm50v508hq.apps.googleusercontent.com',
    iosClientId: '204519090912-o4cj9tmfk81fcri9cfql03ntkg4nk1n5.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanoFinance',
  );
}
